variant::estimated_size()
eosnetworkfoundation/mandel-fc pull request #17
Opened 2022-04-20 17:07 UTC by ClaytonCalabrese

### Adds estimated_size() function to get an estimated size in bytes of a variant.

This a recursive function that will sum the size of everything within the variant in order to get an estimate of the size of the variant in memory.

2022-04-20 19:00 UTC, swatanabe reviewed
What guarantees exactly is this trying to provide?  I would expect it to be something like: The total memory used by the variant is at most C*estimated_size(), where C is a constant that may depend on the platform and is ideally close to 1.  Or is it also supposed to provide a lower bound: the ratio estimated_size()/actual size is in some constant range [min,max]?

2022-04-20 19:00 UTC, swatanabe commented on include/fc/variant.hpp
> +        size_t                        estimated_size();
const

2022-04-20 19:00 UTC, swatanabe commented on src/variant.cpp
> +      return as_string().length();
array and blob both include space for the size.  string probably should as well.

2022-04-20 19:00 UTC, swatanabe commented on src/variant.cpp
> +   size_t sum = 0;
Variables should be declared more locally.

2022-04-20 19:00 UTC, swatanabe commented on src/variant.cpp
> +      return 0;
If null has an estimated size of zero, then a large array of null elements will have a fixed estimated size of 8.

2022-04-20 19:00 UTC, swatanabe commented on src/variant_object.cpp
> +      size_t sum = 0;
An empty object will have an estimated size of 0, which has the same problem as null being 0.

2022-04-20 19:10 UTC, heifner requested changes

2022-04-20 19:10 UTC, heifner commented on src/variant.cpp
> +      return 0;
Add in `sizeof(*this)` for all cases.
For `null_type`, `int64_type`, `uint64_type`, `double_type`, `bool_type` it will only be `sizeof(this)`.
For `string_type` it is `sizeof(*this) + get_string().size()`
For `array_type`, `object_type`, `blob_type` add in `sizeof(*this)`

2022-04-20 19:10 UTC, heifner commented on src/variant.cpp
> +      sum += sizeof(size_t);
Add {} to case and move variable definitions down to here.
Use `get_array()` to avoid calling get_array() over and over in the loop.

2022-04-20 19:10 UTC, heifner commented on src/variant.cpp
> +      sum += sizeof(size_t);
Should be sizeof the `variants` not `size_t`

2022-04-20 19:10 UTC, heifner commented on src/variant.cpp
> +      sum += sizeof(size_t);
Remove this sizeof. blob_type is just size of the vector plus data.size() plus sizeof(*this)

2022-04-20 19:10 UTC, heifner commented on src/variant_object.cpp
> +      return sum;
Add in sizeof(*this) plus sizeof(vector) plus what you have here.

2022-04-21 00:37 UTC, heifner commented on src/variant.cpp
> +      auto arr = get_array();
const auto& to avoid copy.

2022-04-21 19:16 UTC, heifner approved these changes

2022-04-22 15:18 UTC, merged