Add support functions for the new EVM intrinsics
eosnetworkfoundation/mandel-fc pull request #26
Opened 2022-05-25 18:58 UTC by elmato

2022-05-26 16:55 UTC, larryk85 requested changes

2022-05-26 16:55 UTC, larryk85 commented on include/fc/crypto/blake2.hpp
> +        uint64_t h[8];
Adding default initialization here will help the compiler optimize those instructions and reschedule them best.

`uint64_t h[8] = {0,0,0,0,0,0,0,0};`
`uint64_t t[2]  = {0,0};`
`uint64_t f[2]  = {0,0};`

2022-05-26 16:55 UTC, larryk85 commented on src/crypto/blake2.cpp
> +    memset(&state, 0, sizeof(blake2b_state));
This can be removed if you add initialization for `blake2b_state`.

2022-05-26 16:55 UTC, larryk85 commented on include/fc/crypto/blake2.hpp
> +        uint64_t t[2];
Is there a reason that `f` is 16 bytes wide?  It seems to only be setting 8 bytes.

2022-05-26 16:55 UTC, larryk85 commented on src/crypto/blake2.cpp
> +    v[15] = blake2b_IV[7] ^ S->f[1];
This seems to always be zero.

2022-05-26 16:55 UTC, larryk85 commented on src/crypto/ecrecover.cpp
> +            return std::make_pair(ecrecover_error::init_error, bytes{});
Seems like this should hard assert (throw exception) as I'm not sure how we can recover from that.

2022-05-26 16:55 UTC, larryk85 commented on src/crypto/ecrecover.cpp
> +        size_t kOutLen{65};
Add `const` or `constexpr`.

2022-05-26 16:55 UTC, larryk85 commented on src/crypto/modular_arithmetic.cpp
> +        mpz_init(base);
You can do something like:
```c++
mpz_t base, exponent, modulus;
mpz_inits(base, exponent, modulus, nullptr);
```

And then at the clear.
```c++
mpz_clears(base, exponent, modulus, nullptr);
```

Should be slightly faster as its grabbing memory at once and freeing the memory at once.

2022-06-02 18:45 UTC, larryk85 requested changes
SHA3IUF submodule is still present.  I will approve after that one small issue is addressed.  The bigger concerns of how to manage GMP is beyond the scope of this and can be amended after this is merged.

2022-06-02 22:06 UTC, larryk85 submitted a review, later dismissed

2022-06-03 02:22 UTC, spoonincode commented on src/crypto/blake2.cpp
> +#include <string.h>
This file needs to include <limits>, it doesn't build on gcc12 for me otherwise

2022-06-03 03:27 UTC, spoonincode commented on src/crypto/sha3.cpp
> + * than or equal to 1.1.1, we should replace with their primitives.
what's this comment about. mandel requires openssl 1.1+ now

2022-06-03 03:31 UTC, larryk85 commented on src/crypto/blake2.cpp
> +#include <string.h>
You beat me to it. I just now tried to build it too.

Also, its small but change out <stdint.h> and <string.h> to <cstdint> and <cstring> accordingly to ensure that it is including from libcxx.

2022-06-06 21:43 UTC, larryk85 approved these changes

2022-06-08 05:55 UTC, larryk85 approved these changes

2022-06-14 01:25 UTC, merged